### ISSUE TITLE
Make README.md file

### ISSUE THREAD

**Issue by AlanRoybal** [CSAllenISD/2023-ISP-AutomatedWindowShades#2]
Make README.md file and format correctly.

**Comment by HengYiLee** [comment]
The README.md file seems to be correctly detailed with everything necessary for current and future use. This SHOULD NOT be changed for the foreseeable future unless the nature of the project itself changes.

**Comment by adheesh-k** [comment]
README.md file is complete and formatted with team members, roles, GitHub usernames, GitHub profile links, and in-depth project description.
