### ISSUE TITLE
research weather api

### ISSUE THREAD

**Issue by adheesh-k** [CSAllenISD/2023-ISP-AutomatedWindowShades#7]
Begin researching how to connect our product to a weather API. We also need to look at how to pull information from that weather API.

**Comment by AlanRoybal** [comment]
Will the API update off temperature or the amount of sunlight? We should look at combining both of these as well as the information from the light sensors if we go that route.

**Comment by adheesh-k** [comment]
In my opinion, we should look at as many factors as possible. Looking at the level of sunlight through UV index, outside temperature, wind speed, etc. In a home, windows obviously let in sunlight but also are weak points in the home because they do not have much insulation compared to walls. Multiple weather-related factors can have a measurable impact on the indoor temperature from windows, so it is important that we look at as much as possible in order to regulate temperature and sunlight properly and minimize energy costs.

**Comment by adheesh-k** [comment]
> Will the API update off temperature or the amount of sunlight? We should look at combining both of these as well as the information from the light sensors if we go that route.

The use of light sensors is also a good idea because sunlight is the main factor that we need to account for, as that is the main purpose of a window shade. In contrast to the Weather API, which usually can give us a UV index, a light sensor can give us a more instantaneous and relevant reading to determine whether to open or close the window shade.

**Comment by HengYiLee** [comment]
I believe looking at too many factors would cause unnecessary complexity in our system. For example, the wind speed has a non significant impact on the amount of sunlight that will be passing through the window of the house that this will be implemented on. 

> In my opinion, we should look at as many factors as possible by looking at the level of sunlight through UV index, outside temperature, wind speed, etc. In a home, windows obviously let in sunlight but also are weak points in the home because they do not have much insulation compared to walls. Multiple weather-related factors can have a measurable impact on the indoor temperature from windows, so it is important that we look at as much as possible in order to regulate temperature and sunlight properly and minimize energy costs.

**Comment by HengYiLee** [comment]
> Will the API update off temperature or the amount of sunlight? We should look at combining both of these as well as the information from the light sensors if we go that route.

I believe using an illuminance meter to measure the amount of light passing through the window of the house would be the best way to the activation of the window shade. This factor combined with outside temperature from the Weather API would create a robust system that would suit the needs of the product.

**Comment by adheesh-k** [comment]
Some examples of weather APIs that we could use:

- [OpenWeatherMap](https://openweathermap.org/api)
- [tomorrow.io](https://www.tomorrow.io/weather-api/)
- [National Weather Service](https://www.weather.gov/documentation/services-web-api)
- [AccuWeather](https://developer.accuweather.com/)
- [weatherstack](https://weatherstack.com/)

We should evaluate these options (as well as others not listed) in order to see which one best fits our needs.

**Comment by adheesh-k** [comment]
> I believe looking at too many factors would cause unnecessary complexity in our system. For example, the wind speed has a non significant impact on the amount of sunlight that will be passing through the window of the house that this will be implemented on.
> 
> > In my opinion, we should look at as many factors as possible by looking at the level of sunlight through UV index, outside temperature, wind speed, etc. In a home, windows obviously let in sunlight but also are weak points in the home because they do not have much insulation compared to walls. Multiple weather-related factors can have a measurable impact on the indoor temperature from windows, so it is important that we look at as much as possible in order to regulate temperature and sunlight properly and minimize energy costs.

I agree that sunlight is the most significant factor, but if we can implement other factors in order to get a more accurate reading in order to drive down energy costs without overcomplicating our system, we should do so.

**Comment by adheesh-k** [comment]
We have chosen to use OpenWeatherMap as our weather API for the time being, as we want to start with our software development. If we find a better API in the future, we can always switch it out.

**Comment by HengYiLee** [comment]
> Some examples of weather APIs that we could use:
> 
> * [OpenWeatherMap](https://openweathermap.org/api)
> * [tomorrow.io](https://www.tomorrow.io/weather-api/)
> * [National Weather Service](https://www.weather.gov/documentation/services-web-api)
> * [AccuWeather](https://developer.accuweather.com/)
> * [weatherstack](https://weatherstack.com/)
> 
> We should evaluate these options (as well as others not listed) in order to see which one best fits our needs.

I believe that OpenWeatherMap would be the best option amongst those listed and not listed. A better API may be found in the future, but for now, OpenWeatherMap is the best option.

**Comment by HengYiLee** [comment]
> > I believe looking at too many factors would cause unnecessary complexity in our system. For example, the wind speed has a non significant impact on the amount of sunlight that will be passing through the window of the house that this will be implemented on.
> > > In my opinion, we should look at as many factors as possible by looking at the level of sunlight through UV index, outside temperature, wind speed, etc. In a home, windows obviously let in sunlight but also are weak points in the home because they do not have much insulation compared to walls. Multiple weather-related factors can have a measurable impact on the indoor temperature from windows, so it is important that we look at as much as possible in order to regulate temperature and sunlight properly and minimize energy costs.
> 
> I agree that sunlight is the most significant factor, but if we can implement other factors in order to get a more accurate reading in order to drive down energy costs without overcomplicating our system, we should do so.

Implementing other factors may in fact get us a less accurate reading, and drive down energy costs all while our system is more complicated and fixing it will be more difficult. 
For example, wind speed being a variable impacting the amount of sunlight that will be passing through the window of the house that this will be implemented on could lead to less than ideal sunlight or more sunlight which would lead to increased energy costs.
Adding variables that have little to no improvement on the end product while compromising the entire system is a risk that SHOULD NOT be taken. In fact, the variable stated may have such a small impact that the motor used may not be physically able to account for such a small change in rotation.

**Comment by adheesh-k** [comment]
> > > I believe looking at too many factors would cause unnecessary complexity in our system. For example, the wind speed has a non significant impact on the amount of sunlight that will be passing through the window of the house that this will be implemented on.
> > > > In my opinion, we should look at as many factors as possible by looking at the level of sunlight through UV index, outside temperature, wind speed, etc. In a home, windows obviously let in sunlight but also are weak points in the home because they do not have much insulation compared to walls. Multiple weather-related factors can have a measurable impact on the indoor temperature from windows, so it is important that we look at as much as possible in order to regulate temperature and sunlight properly and minimize energy costs.
> > 
> > 
> > I agree that sunlight is the most significant factor, but if we can implement other factors in order to get a more accurate reading in order to drive down energy costs without overcomplicating our system, we should do so.
> 
> Implementing other factors may in fact get us a less accurate reading, and drive down energy costs all while our system is more complicated and fixing it will be more difficult. For example, wind speed being a variable impacting the amount of sunlight that will be passing through the window of the house that this will be implemented on could lead to less than ideal sunlight or more sunlight which would lead to increased energy costs. Adding variables that have little to no improvement on the end product while compromising the entire system is a risk that SHOULD NOT be taken. In fact, the variable stated may have such a small impact that the motor used may not be physically able to account for such a small change in rotation.

I will open a new issue for necessary weather factors that we should take into account. We can discuss this further and see  which factors we need through our testing.

**Comment by adheesh-k** [comment]
> > Some examples of weather APIs that we could use:
> > 
> > * [OpenWeatherMap](https://openweathermap.org/api)
> > * [tomorrow.io](https://www.tomorrow.io/weather-api/)
> > * [National Weather Service](https://www.weather.gov/documentation/services-web-api)
> > * [AccuWeather](https://developer.accuweather.com/)
> > * [weatherstack](https://weatherstack.com/)
> > 
> > We should evaluate these options (as well as others not listed) in order to see which one best fits our needs.
> 
> I believe that OpenWeatherMap would be the best option amongst those listed and not listed. A better API may be found in the future, but for now, OpenWeatherMap is the best option.

Looks like OpenWeatherMap is our best option and this is what we will use going forward. I will reopen this issue if we run into any major problems and need to consider switching to another one.
