### ISSUE TITLE
Connect local repositories

### ISSUE THREAD

**Issue by adheesh-k** [CSAllenISD/2023-ISP-AutomatedWindowShades#9]
Connect the local repositories of all team members to ensure there are no merge complications.

**Comment by HengYiLee** [comment]
All team members seem to have connected their local repositories to Github to create a single repository. This will not be required to be done again UNLESS a team member uses another local machine, in which that local machine will need to be connected to Github.

**Comment by adheesh-k** [comment]
My local repository is connected and is working properly.

**Comment by HengYiLee** [comment]
My local repository is connected and is working properly.

**Comment by AlanRoybal** [comment]
My local repository is connected and is working properly.

**Comment by adheesh-k** [comment]
Everyone in the team has their local repositories connected.
